version: 0.0
os: linux
files:
   - source: /
     destination: /var/urlshortnerdemo
hooks:
   AfterInstall:
    - location: scripts/dotnetrun.sh
      runas: root
   BeforeInstall:
    - location: scripts/dotnetstop.sh
      runas: root
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
     runas: root
  ApplicationStart:
    - location: register_with_elb.sh
      runas: root
