version: 0.0
os: linux
files:
   - source: /
     destination: /var/urlshortnerdemo
hooks:
   AfterInstall:
    - location: scripts/dotnetrun.sh
      runas: root
   ApplicationStart:
    - location: scripts/register_with_elb.sh
